export const ISOCENTERED_MAGNET = 'Isocentered Magnet';
export const TAU_GRADE_RHEOSTAT = 'Tau Grade Rheostat';
export const AUSTENITIC_MANIFOLD = 'Austenitic Manifold';
export const ISOTOPIC_COOLANT = 'Isotopic Coolant';
export const MAG_PRESSURE_TANK = 'Mag Pressure Tank';
export const REACTIVE_GAUGE = 'Reactive Gauge';
export const ZERO_WIRE = 'Zero Wire';
export const COMM_RELAY = 'Comm Relay';
export const MONOPROPELLANT = 'Monopropellant';